services:
    node:
        restart: unless-stopped
        user: '${USER_ID}:${GROUP_ID}'
        build:
            context: .
        ports:
            - '3001:3000'
        volumes:
            - .:/home/node/app
            - /home/node/app/node_modules
